// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProductService.Persistence;

#nullable disable

namespace MusicFlow.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260713190924_AddDb")]
    partial class AddDb
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MusicFlow.Domain.Entites.Artist", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Artists");

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111111"),
                            Country = "Egypt",
                            Email = "ahmed@test.com",
                            Name = "Ahmed Ali"
                        },
                        new
                        {
                            Id = new Guid("10000000-1111-1111-1111-111111111111"),
                            Country = "Tunis",
                            Email = "tamer@test.com",
                            Name = "Tamer Nour"
                        },
                        new
                        {
                            Id = new Guid("20000000-1111-1111-1111-111111111111"),
                            Country = "Saudia",
                            Email = "mona@test.com",
                            Name = "Mona Yasser"
                        });
                });

            modelBuilder.Entity("MusicFlow.Domain.Entites.DSP", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("DSPs");

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-2222-2222-2222-222222222222"),
                            Name = "Spotify"
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222222"),
                            Name = "Youtube"
                        },
                        new
                        {
                            Id = new Guid("33333333-2222-2222-2222-222222222222"),
                            Name = "TickTock"
                        });
                });

            modelBuilder.Entity("MusicFlow.Domain.Entites.Track", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ArtistId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Genre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ISRC")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly>("ReleaseDate")
                        .HasColumnType("date");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ArtistId");

                    b.ToTable("Tracks");

                    b.HasData(
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333333"),
                            ArtistId = new Guid("11111111-1111-1111-1111-111111111111"),
                            Genre = "Pop",
                            ISRC = "US-AAA-23-00001",
                            ReleaseDate = new DateOnly(2023, 1, 1),
                            Status = 3,
                            Title = "Track 1"
                        },
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-444444444444"),
                            ArtistId = new Guid("10000000-1111-1111-1111-111111111111"),
                            Genre = "Pop",
                            ISRC = "US-AAA-93-00002",
                            ReleaseDate = new DateOnly(2024, 1, 1),
                            Status = 2,
                            Title = "Track 2"
                        },
                        new
                        {
                            Id = new Guid("55555555-3333-3333-3333-333333333333"),
                            ArtistId = new Guid("20000000-1111-1111-1111-111111111111"),
                            Genre = "Pop",
                            ISRC = "US-AAA-23-00003",
                            ReleaseDate = new DateOnly(2020, 1, 1),
                            Status = 3,
                            Title = "Track 3"
                        },
                        new
                        {
                            Id = new Guid("66666666-4444-4444-4444-444444444444"),
                            ArtistId = new Guid("10000000-1111-1111-1111-111111111111"),
                            Genre = "Pop",
                            ISRC = "US-AAA-93-00004",
                            ReleaseDate = new DateOnly(2021, 1, 1),
                            Status = 2,
                            Title = "Track 4"
                        },
                        new
                        {
                            Id = new Guid("77777777-3333-3333-3333-333333333333"),
                            ArtistId = new Guid("11111111-1111-1111-1111-111111111111"),
                            Genre = "Pop",
                            ISRC = "US-AAA-23-00005",
                            ReleaseDate = new DateOnly(2025, 1, 1),
                            Status = 3,
                            Title = "Track 5"
                        },
                        new
                        {
                            Id = new Guid("88888888-4444-4444-4444-444444444444"),
                            ArtistId = new Guid("10000000-1111-1111-1111-111111111111"),
                            Genre = "Pop",
                            ISRC = "US-AAA-93-00006",
                            ReleaseDate = new DateOnly(2026, 1, 1),
                            Status = 2,
                            Title = "Track 6"
                        },
                        new
                        {
                            Id = new Guid("99999999-3333-3333-3333-333333333333"),
                            ArtistId = new Guid("11111111-1111-1111-1111-111111111111"),
                            Genre = "Pop",
                            ISRC = "US-AAA-23-00007",
                            ReleaseDate = new DateOnly(2019, 1, 1),
                            Status = 3,
                            Title = "Track 7"
                        },
                        new
                        {
                            Id = new Guid("11112211-4444-4444-4444-444444444444"),
                            ArtistId = new Guid("10000000-1111-1111-1111-111111111111"),
                            Genre = "Pop",
                            ISRC = "US-AAA-93-00008",
                            ReleaseDate = new DateOnly(2018, 1, 1),
                            Status = 2,
                            Title = "Track 8"
                        });
                });

            modelBuilder.Entity("MusicFlow.Domain.Entites.TrackDistribution", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("DspId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime>("SubmittedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("TrackId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("DspId");

                    b.HasIndex("TrackId");

                    b.ToTable("TrackDistributions");
                });

            modelBuilder.Entity("MusicFlow.Domain.Entites.Track", b =>
                {
                    b.HasOne("MusicFlow.Domain.Entites.Artist", "Artist")
                        .WithMany("Tracks")
                        .HasForeignKey("ArtistId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Artist");
                });

            modelBuilder.Entity("MusicFlow.Domain.Entites.TrackDistribution", b =>
                {
                    b.HasOne("MusicFlow.Domain.Entites.DSP", "Dsp")
                        .WithMany("TrackDistributions")
                        .HasForeignKey("DspId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MusicFlow.Domain.Entites.Track", "Track")
                        .WithMany("TrackDistributions")
                        .HasForeignKey("TrackId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Dsp");

                    b.Navigation("Track");
                });

            modelBuilder.Entity("MusicFlow.Domain.Entites.Artist", b =>
                {
                    b.Navigation("Tracks");
                });

            modelBuilder.Entity("MusicFlow.Domain.Entites.DSP", b =>
                {
                    b.Navigation("TrackDistributions");
                });

            modelBuilder.Entity("MusicFlow.Domain.Entites.Track", b =>
                {
                    b.Navigation("TrackDistributions");
                });
#pragma warning restore 612, 618
        }
    }
}
